# Generated by Django 5.1 on 2024-08-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField()),
                ('date_updated', models.DateTimeField()),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
