# Generated by Django 5.1 on 2024-08-30 16:21

from django.db import migrations, models


def convert_size_to_bytes(apps, schema_editor):
    File = apps.get_model('api', 'File')
    for file in File.objects.all():
        size_str = file.size
        if 'КБ' in size_str:
            file.size = int(size_str.replace(' КБ', '')) * 1024
        elif 'МБ' in size_str:
            file.size = int(size_str.replace(' МБ', '')) * 1024 * 1024
        elif 'ГБ' in size_str:
            file.size = int(size_str.replace(' ГБ', '')) * 1024 * 1024 * 1024
        file.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_file'),
    ]

    operations = [
        migrations.RunPython(convert_size_to_bytes),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(),
        ),
    ]
